### PR TITLE
fix: DHCPv6 does not respect prefix assigned to interface (>= /64)

### LINKED ISSUE #199: bug: DHCPv6 does not respect prefix assigned to interface (<=/64)
When odhcpd hands out IPv6 leases on an interface with a prefix <=/64 (e.g. /96), leases can (and often are) outside of the allocated /96 on the interface.
I've looked a bit at the code and it seems the host_id calculation always infers 64bit, thus a /64 prefix. I would've expected odhcpd in DHCPv6 server mode, to actually respect the assigned prefix.

Are you open PR to fix this?

### PR DESCRIPTION
**Pull request by xvzf**
fixes #199

Signed-off-by: Matthias Riegler <matthias.riegler@ankorstore.com>

### CODE REVIEW

**Comment by systemcrash** [comment]
ping @dedeckeh @Noltari 

This fixes an edge case (see "Fixes" discussion).

File: src/dhcpv6-ia.c [hunk 1]
```diff
@@ -834,6 +844,23 @@ static bool is_reserved_ipv6_iid(uint64_t iid)
...
+static uint32_t mask_high_for_hostid(uint8_t dhcpv6_hostid_len) {
+	if (dhcpv6_hostid_len >= 64)
+		return UINT32_MAX;
+
+  if (dhcpv6_hostid_len >= 32)
+    return (1 << (dhcpv6_hostid_len - 32)) - 1;
+
+	return 0;
+}
+
```
Comment (Noltari) [inline src/dhcpv6-ia.c]: I think we should move these to functions to the top and make them inline.
That way we don't need to add declarations at the top.

File: src/dhcpv6-ia.c [hunk 2]
```diff
@@ -834,6 +844,23 @@ static bool is_reserved_ipv6_iid(uint64_t iid)
 	return false;
 }
 
+static uint32_t mask_low_for_hostid(uint8_t dhcpv6_hostid_len) {
```
Comment (Noltari) [inline src/dhcpv6-ia.c]: Please, move the `{` to the next line:
```
static uint32_t mask_low_for_hostid(uint8_t dhcpv6_hostid_len)
{
```

File: src/dhcpv6-ia.c [hunk 3]
```diff
@@ -834,6 +844,23 @@ static bool is_reserved_ipv6_iid(uint64_t iid)
...
+	if (dhcpv6_hostid_len >= 32)
+		return UINT32_MAX;
+
+	return (1 << dhcpv6_hostid_len) - 1;
+}
+
+static uint32_t mask_high_for_hostid(uint8_t dhcpv6_hostid_len) {
```
Comment (Noltari) [inline src/dhcpv6-ia.c]: Please, move the `{` to the next line:
```
static uint32_t mask_high_for_hostid(uint8_t dhcpv6_hostid_len)
{
```

File: src/dhcpv6-ia.c [hunk 4]
```diff
@@ -249,8 +251,16 @@ void dhcpv6_ia_enum_addrs(struct interface *iface, struct dhcp_assignment *c,
 			if (!ADDR_ENTRY_VALID_IA_ADDR(iface, i, m, addrs))
 				continue;
 
-			addr.s6_addr32[2] = htonl(c->assigned_host_id >> 32);
-			addr.s6_addr32[3] = htonl(c->assigned_host_id & UINT32_MAX);
+			uint32_t mask_low = mask_low_for_hostid(iface->dhcpv6_hostid_len);
+			uint32_t mask_high = mask_high_for_hostid(iface->dhcpv6_hostid_len);
```
Comment (Noltari) [inline src/dhcpv6-ia.c]: Can we move the `uint32_t` declarations to the start of the block?
```
if (c->flags & OAF_DHCPV6_NA) {
	uint32_t mask_high, mask_low;

	if (!ADDR_ENTRY_VALID_IA_ADDR(iface, i, m, addrs))
		continue;

	mask_high = mask_high_for_hostid(iface->dhcpv6_hostid_len);
	mask_low = mask_low_for_hostid(iface->dhcpv6_hostid_len);

	...
}
```

File: src/dhcpv6-ia.c [hunk 5]
```diff
@@ -860,27 +887,22 @@ static bool assign_na(struct interface *iface, struct dhcp_assignment *a)
...
-			else
-				mask_low = (1 << iface->dhcpv6_hostid_len) - 1;
+		} else {
+			uint32_t mask_low = mask_low_for_hostid(iface->dhcpv6_hostid_len);
 			do try = ((uint32_t)random()) & mask_low; while (try < 0x100);
 		}
 
+    // If prefix is < 64 bits, we need to shift the IID to the left
+    if (iface->addr6_len < 64)
+      try <<= (64 - iface->addr6_len);
```
Comment (Noltari) [inline src/dhcpv6-ia.c]: Please indent this properly with tabs.

File: src/dhcpv6-ia.c [hunk 6]
```diff
@@ -834,6 +844,23 @@ static bool is_reserved_ipv6_iid(uint64_t iid)
...
+
+	return (1 << dhcpv6_hostid_len) - 1;
+}
+
+static uint32_t mask_high_for_hostid(uint8_t dhcpv6_hostid_len) {
+	if (dhcpv6_hostid_len >= 64)
+		return UINT32_MAX;
+
+  if (dhcpv6_hostid_len >= 32)
+    return (1 << (dhcpv6_hostid_len - 32)) - 1;
```
Comment (Noltari) [inline src/dhcpv6-ia.c]: Please indent this properly with tabs.

File: src/dhcpv6-ia.c [hunk 7]
```diff
@@ -249,8 +251,16 @@ void dhcpv6_ia_enum_addrs(struct interface *iface, struct dhcp_assignment *c,
...
+			uint32_t mask_low = mask_low_for_hostid(iface->dhcpv6_hostid_len);
+			uint32_t mask_high = mask_high_for_hostid(iface->dhcpv6_hostid_len);
+			addr.s6_addr32[2] = htonl((
+					(c->assigned_host_id >> 32) & mask_high)
+					& (~mask_high & ntohl(addrs[i].addr.in6.s6_addr32[2])
+				));
+			addr.s6_addr32[3] = htonl((
+					(c->assigned_host_id & UINT32_MAX) & mask_low)
+					& (~mask_low & ntohl(addrs[i].addr.in6.s6_addr32[3])
+				));
```
Comment (Noltari) [inline src/dhcpv6-ia.c]: Remove the double `(( .. ))` from `htnol`.

**Review by Noltari — CHANGES_REQUESTED** [review]

**Comment by systemcrash** [comment]
Still needs fixes @xvzf

File: src/dhcpv6-ia.c (hunk 5 above)
Comment (systemcrash) [reply src/dhcpv6-ia.c]: @xvzf

File: src/dhcpv6-ia.c [hunk 8]
```diff
@@ -860,27 +889,22 @@ static bool assign_na(struct interface *iface, struct dhcp_assignment *a)
...
-			if (iface->dhcpv6_hostid_len == 32)
-				mask_low = UINT32_MAX;
-			else
-				mask_low = (1 << iface->dhcpv6_hostid_len) - 1;
+		} else {
+			uint32_t mask_low = mask_low_for_hostid(iface->dhcpv6_hostid_len);
 			do try = ((uint32_t)random()) & mask_low; while (try < 0x100);
 		}
 
+    // If prefix is < 64 bits, we need to shift the IID to the left
```
Comment (systemcrash) [inline src/dhcpv6-ia.c]: InterfaceID

File: src/dhcpv6-ia.c (hunk 7 above)
Comment (systemcrash) [reply src/dhcpv6-ia.c]: @xvzf

File: src/dhcpv6-ia.c [hunk 9]
```diff
@@ -249,8 +270,16 @@ void dhcpv6_ia_enum_addrs(struct interface *iface, struct dhcp_assignment *c,
...
 				continue;
 
-			addr.s6_addr32[2] = htonl(c->assigned_host_id >> 32);
-			addr.s6_addr32[3] = htonl(c->assigned_host_id & UINT32_MAX);
+			mask_low = mask_low_for_hostid(iface->dhcpv6_hostid_len);
+			mask_high = mask_high_for_hostid(iface->dhcpv6_hostid_len);
+			addr.s6_addr32[2] = htonl((
+					(c->assigned_host_id >> 32) & mask_high)
+					& (~mask_high & ntohl(addrs[i].addr.in6.s6_addr32[2])
+				));
```
Comment (systemcrash) [inline src/dhcpv6-ia.c]: here also @xvzf

**Comment by Noltari** [comment]
I think I've fixed all the comments myself, so please @systemcrash confirm when you can and I'll merge this.

File: src/dhcpv6-ia.c [hunk 10]
```diff
@@ -249,8 +269,16 @@ void dhcpv6_ia_enum_addrs(struct interface *iface, struct dhcp_assignment *c,
...
-			addr.s6_addr32[3] = htonl(c->assigned_host_id & UINT32_MAX);
+			mask_low = mask_low_for_hostid(iface->dhcpv6_hostid_len);
+			mask_high = mask_high_for_hostid(iface->dhcpv6_hostid_len);
+			addr.s6_addr32[2] = htonl(
+				((c->assigned_host_id >> 32) & mask_high)
+				& (~mask_high & ntohl(addrs[i].addr.in6.s6_addr32[2]))
+			);
+			addr.s6_addr32[3] = htonl(
+				((c->assigned_host_id & UINT32_MAX) & mask_low)
+				& (~mask_low & ntohl(addrs[i].addr.in6.s6_addr32[3]))
```
Comment (systemcrash) [inline src/dhcpv6-ia.c:280]: these?

Comment (systemcrash) [reply src/dhcpv6-ia.c:280]: Ah sorry. Blind. All good :)

Comment (Noltari) [reply src/dhcpv6-ia.c:280]: Do you mean the double parentheses that I reported?
If that's the case they are needed but they were poorly placed in different lines and I've moved them where they belong.

**Comment by systemcrash** [comment]
LGTM

**Comment by systemcrash** [comment]
Actually, can you reword the commit message so it says >= 64?

**Comment by systemcrash** [comment]
I know - it's sometimes confusing. But in math 96 > 64. A 96 bit prefix is in fact greater than a 64 bit prefix, though the result is that the subnet space is 'smaller' as a result.

**Comment by Noltari** [comment]
Merged, thanks @xvzf!

**Comment by xvzf** [comment]
Thx @Noltari and sorry for not getting back earlier to this; has been dangling around quite long
